### ISSUE TITLE
Upload to npm

### ISSUE THREAD

**Issue by tscpp** [liljencrantz/crush#21]
<div align="justify">

When I first tried to install crush, I did it with [npm](https://www.npmjs.com/), but it didn't work<sup>1</sup>, so I would appreciate if it could be uploaded to npm. This has some requirements though, of them is that npm requires [semantic versioning aka samver](https://semver.org/), which will restrict how pull requests can be accepted. <sup>1</sup>There is one problem left [crush](https://npmjs.com/package/crush) is occupied by another project. The good news is that the crush package on npm has 0 weekly downloads and hasn't been updated for six years; therefore it could be possible to get the package anyways by contacting the [owner](https://www.npmjs.com/~kenan) or [npm](mailto:support@npmjs.com). I would like to contribute with a pull request.

</div>

**Comment by liljencrantz** [comment]
Is npm a suitable packacge manager for rust commands? I would have imagined that a crate would be more suitable, but I'm not that familiar with modern usages of npm.

**Comment by liljencrantz** [comment]
If you make the effort to package crush for npm, I will assist you any way I can.

**Comment by tscpp** [comment]
I made a pull request with the necessary files to publish: #27.

**Comment by tscpp** [comment]
I am closing this because npm is the "node package manager" and rust crates does not belong there.
