### ISSUE TITLE
Keep * as glob pattern

### ISSUE THREAD

**Issue by koppor** [liljencrantz/crush#7]
The `README.md` states:

![grafik](https://user-images.githubusercontent.com/1366654/78489360-4fe54e80-7748-11ea-9214-16aaa0b07fe5.png)

glob was always, is and will be always use `*`. See https://en.wikipedia.org/wiki/Glob_(programming) 😇 

I bet that multiplicaton is used less in shells than matching "any number of any characters".

Please keep `*`  as glob pattern and use something else than `*` for multiplication.

`/` is also kept as normal shell pattern and not as token for division.

Ideas:

- Use `\*` (could be difficult for other escapings)
- Use `MUL` (could be strange as not consistent to divide)
- Use `times` (idea from https://en.wikipedia.org/wiki/Multiplication_sign)

**Comment by liljencrantz** [comment]
IIRC, SQL also uses % as the glob pattern, no?

Not saying you're wrong, maybe this should be changed, just pointing out that there is precentent for using % for globs outside of crush.

**Comment by koppor** [comment]
Ah, yeah! - I was just thinking what does prevent me from using Crush as default shell. Currently I am using git bash and cmd.exe (with [Clink](https://mridgers.github.io/clink/)) depending on the use case (being in a git repository directory or not).

**Comment by aaronjanse** [comment]
I'd like to note that `*` should still work with bash/sh/zsh/etc scripts being called via crush. I'm personally in favor of `%`, but I think `*` vs `%` is more of a matter of preference than anything else. Regardless, thank you for creating this @liljencrantz!

**Comment by vadim-goryunov** [comment]
If you are interested in another opinion on this subject: extract any arithmetic operations into a separate function (e.g. calc) and accept a commonly used syntax there. i.e. force people to use the function to calculate anything.
Then keep * for glob.

Example:
`crush> calc 4 * 5 / 2`
`10`
`crush> wavg := { |a, b, wa, wb| calc (a*wa + b*wb) / (wa + wb) ) }`
`crush> wavg 2 5 10 40`
`4.4`
`crush> 4 * 5 / 2`
`syntax error`

`crush> ls *.txt`
`... <print files with txt extensions> ...`

You can accept some arithmetic related keywords (like sin or cos or ^2 for square) inside that calc function to enhance the possibilities in the future.
Would be also nice to just type calc to switch into a calculations mode
`crush> calc`
`crush::calc>`
and then being able to use crush as command line calculator
`crush::calc> 2* 4` 
`8`

**Comment by koppor** [comment]
I see that people using this shell should know more SQL ^^.

This calls for an [ADR](https://adr.github.io/madr/).
